(define (problem problemBasic)
    (:domain domainP)
    
    (:objects
        ex1 ex2 ex3 ex4 est1 est2 est3 est4 - exercici
        n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 - nivell
        d0 d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 - dia
        q0 q1 q2 q3 q4 q5 q6 - quantitat
    )
    
    (:init
        (preparador est1 ex1)
        (precursor ex2 ex1)
        (preparador est2 ex2)
        (preparador est3 ex3)
        (preparador est4 ex4)
        (noprep est1)
        (noprep est2)
        (noprep est3)
        (noprep est4)
        (noprec ex2)
        (noprec ex3)
        (noprec ex4)
        (noprec est1)
        (noprec est2)
        (noprec est3)
        (noprec est4)


        (dia_abans d0 d1)

        (dia_abans d1 d2)

        (dia_abans d1 d3)
        (dia_abans d2 d3)

        (dia_abans d1 d4)
        (dia_abans d2 d4)
        (dia_abans d3 d4)

        (dia_abans d1 d5)
        (dia_abans d2 d5)
        (dia_abans d3 d5)
        (dia_abans d4 d5)

        (dia_abans d1 d6)
        (dia_abans d2 d6)
        (dia_abans d3 d6)
        (dia_abans d4 d6)
        (dia_abans d5 d6)

        (dia_abans d1 d7)
        (dia_abans d2 d7)
        (dia_abans d3 d7)
        (dia_abans d4 d7)
        (dia_abans d5 d7)
        (dia_abans d6 d7)

        (dia_abans d1 d8)
        (dia_abans d2 d8)
        (dia_abans d3 d8)
        (dia_abans d4 d8)
        (dia_abans d5 d8)
        (dia_abans d6 d8)
        (dia_abans d7 d8)

        (dia_abans d1 d9)
        (dia_abans d2 d9)
        (dia_abans d3 d9)
        (dia_abans d4 d9)
        (dia_abans d5 d9)
        (dia_abans d6 d9)
        (dia_abans d7 d9)
        (dia_abans d8 d9)

        (dia_abans d1 d10)
        (dia_abans d2 d10)
        (dia_abans d3 d10)
        (dia_abans d4 d10)
        (dia_abans d5 d10)
        (dia_abans d6 d10)
        (dia_abans d7 d10)
        (dia_abans d8 d10)
        (dia_abans d9 d10)

        (dia_abans d1 d11)
        (dia_abans d2 d11)
        (dia_abans d3 d11)
        (dia_abans d4 d11)
        (dia_abans d5 d11)
        (dia_abans d6 d11)
        (dia_abans d7 d11)
        (dia_abans d8 d11)
        (dia_abans d9 d11)
        (dia_abans d10 d11)

        (dia_abans d1 d12)
        (dia_abans d2 d12)
        (dia_abans d3 d12)
        (dia_abans d4 d12)
        (dia_abans d5 d12)
        (dia_abans d6 d12)
        (dia_abans d7 d12)
        (dia_abans d8 d12)
        (dia_abans d9 d12)
        (dia_abans d10 d12)
        (dia_abans d11 d12)

        (dia_abans d1 d13)
        (dia_abans d2 d13)
        (dia_abans d3 d13)
        (dia_abans d4 d13)
        (dia_abans d5 d13)
        (dia_abans d6 d13)
        (dia_abans d7 d13)
        (dia_abans d8 d13)
        (dia_abans d9 d13)
        (dia_abans d10 d13)
        (dia_abans d11 d13)
        (dia_abans d12 d13)

        (dia_abans d1 d14)
        (dia_abans d2 d14)
        (dia_abans d3 d14)
        (dia_abans d4 d14)
        (dia_abans d5 d14)
        (dia_abans d6 d14)
        (dia_abans d7 d14)
        (dia_abans d8 d14)
        (dia_abans d9 d14)
        (dia_abans d10 d14)
        (dia_abans d11 d14)
        (dia_abans d12 d14)
        (dia_abans d13 d14)

        (dia_abans d1 d15)
        (dia_abans d2 d15)
        (dia_abans d3 d15)
        (dia_abans d4 d15)
        (dia_abans d5 d15)
        (dia_abans d6 d15)
        (dia_abans d7 d15)
        (dia_abans d8 d15)
        (dia_abans d9 d15)
        (dia_abans d10 d15)
        (dia_abans d11 d15)
        (dia_abans d12 d15)
        (dia_abans d13 d15)
        (dia_abans d14 d15)

        (nivell_ant n0 n1)
        (nivell_ant n1 n2)
        (nivell_ant n2 n3)
        (nivell_ant n3 n4)
        (nivell_ant n4 n5)
        (nivell_ant n5 n6)
        (nivell_ant n6 n7)
        (nivell_ant n7 n8)
        (nivell_ant n8 n9)
        (nivell_ant n9 n10)

        (quant_seg q0 q1)
        (quant_seg q1 q2)
        (quant_seg q2 q3)
        (quant_seg q3 q4)
        (quant_seg q4 q5)
        (quant_seg q5 q6)

        (quant_ex_fets d1 q0)
        (quant_ex_fets d2 q0)
        (quant_ex_fets d3 q0)
        (quant_ex_fets d4 q0)
        (quant_ex_fets d5 q0)
        (quant_ex_fets d6 q0)
        (quant_ex_fets d7 q0)
        (quant_ex_fets d8 q0)
        (quant_ex_fets d9 q0)
        (quant_ex_fets d10 q0)
        (quant_ex_fets d11 q0)
        (quant_ex_fets d12 q0)
        (quant_ex_fets d13 q0)
        (quant_ex_fets d14 q0)
        (quant_ex_fets d15 q0)

    )
    
    (:goal
        (and(nivell_max ex1 n10)
        (nivell_max ex2 n4)
        (nivell_max ex3 n8)
        (nivell_max ex4 n3)
        (nivell_max est1 n1)
        (nivell_max est2 n1)
        (nivell_max est3 n1)
        (nivell_max est4 n1))
    )
)